# Generated by Django 3.1.5 on 2021-01-26 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_group_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.CharField(max_length=250)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
            ],
            options={
                'unique_together': {('email_id', 'course')},
            },
        ),
    ]
